### ISSUE TITLE
How to repair that??

### ISSUE THREAD

**Issue by itzkrofi** [924e50c0/ContextMenuIcons#1]
![image](https://github.com/user-attachments/assets/9f29b8d4-d71e-429f-a5a3-92e040a4f71c)

**Comment by 924e50c0** [comment]
These are the default icons, supposed to be replaced individually.
I wrote the code by separating each context menu, so I'm assuming I completely missed one somewhere, do you remember where you found it? I'm guessing this is a user menu of some kind?

**Comment by itzkrofi** [comment]
i found that menu when i clicked on my friend ppm in voice chat

**Comment by itzkrofi** [comment]
server actions dont work too and everything

**Comment by itzkrofi** [comment]
voice chat actions
![image](https://github.com/user-attachments/assets/96502c9d-86fb-4d75-912e-78361a308a55)

channel actions
![image](https://github.com/user-attachments/assets/9f63b2f2-34fe-42ac-96d2-672547c7415a)


server actions
![image](https://github.com/user-attachments/assets/1769043d-0aaf-4482-9b59-34ba6dc3352f)

**Comment by 924e50c0** [comment]
I'm guessing you are on a different version of discord then?
I wrote the theme on the latest release of [Vesktop](https://github.com/Vencord/Vesktop/releases/tag/v1.5.3) but it works fine with Vencord itself with only a few issues that I need to fix.

Maybe you could paste the whole theme in the vencord quick css, open the devtools and check what could be the problem that way, since I can't replicate it?

**Comment by itzkrofi** [comment]
ye i am on just vencord, i checked devtools and nothing seems to be bad

**Comment by 924e50c0** [comment]
I'm not sure then, maybe it has something to do with the nesting? You could try removing it, although I have no idea why it would cause any issue

**Comment by itzkrofi** [comment]
bro its so weird, i repaired it by just commenting this line 
![image](https://github.com/user-attachments/assets/5e67a4ac-4e05-4352-bba2-e8e2a91fcefe)


now its working like magic
![image](https://github.com/user-attachments/assets/83fe2b9d-f60e-412f-b89f-a62a928131ba)


so, my fix is that you need to comment every line that have "<name> actions"

maybe its working because i have polish language on? and on css its english? idk

but not everything is working fine, like here is thread
![image](https://github.com/user-attachments/assets/4a1f75b2-cf4a-475b-8858-30082fef4767)

**Comment by 924e50c0** [comment]
okay yeah I don't know why I used an accessibility feature that obviously changes depending on the language as a selector, I'm fixing this as soon as I can
The join thread menu I also completely missed thanks for the heads up

**Comment by itzkrofi** [comment]
no problem!

**Comment by 924e50c0** [comment]
It should work properly now. Feel free to open a new issue if you find missing icons
