### ISSUE TITLE
no icons

### ISSUE THREAD

**Issue by itzkrofi** [924e50c0/ContextMenuIcons#3]
its me again, now this happens when i ppm on server channel where i am not admin
![image](https://github.com/user-attachments/assets/4c1fc48a-7286-42cc-8f3c-3e7be973cc36)

it means add to favourite and stop following category

this is when i ppm on category name
![image](https://github.com/user-attachments/assets/bd80291a-13a7-4968-9c51-23f34b423229)

it means remove form channel list something like that

thats a list from clicking an arrow next to server name like you would like to go into server settings
![image](https://github.com/user-attachments/assets/b6113ebe-c22b-44e4-8838-c75ea17bdc17)

it means show all channel

this is for extension
![image](https://github.com/user-attachments/assets/13ce58d3-b724-491d-bb21-9e6d4996832a)

**Comment by itzkrofi** [comment]
oh and of course show all channels when ppm on server icon on the left

![image](https://github.com/user-attachments/assets/7ec7a05f-3170-400f-b04e-4cbf68a3f48c)

**Comment by itzkrofi** [comment]
![image](https://github.com/user-attachments/assets/3f2e86b6-7c85-4879-b887-06d7d1b24e26)
in server options when ppm on icon

**Comment by 924e50c0** [comment]
I have none of these options, are they part of a plugin?

**Comment by itzkrofi** [comment]
security actions arent part of plugin, they are in basic client even without vencord, show all channels too so rest seems to be plugin

**Comment by 924e50c0** [comment]
I found them all and added the icons

**Comment by kruszeleq** [comment]
it works like a charm now

**Comment by itzkrofi** [comment]
works like a charm now, tysm
